document.getElementById('writeHeader').innerHTML = "Create and Store Definition"
document.getElementById('wordLabel').innerHTML= "Word: "
document.getElementById('definitionLabel').innerHTML= "Definition: "
document.getElementById('submitBtn').innerHTML= "Submit"
document.getElementById('confirmPatch').innerHTML= "Yes"
document.getElementById('declinePatch').innerHTML= "No"